on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

name: Build Android APK

jobs:
  build-apk:
    name: Add Android Debug Apk to Release Assets
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: android
    steps:
      - uses: actions/checkout@v4
      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Add google-services.json
        run: |
          echo "${{ secrets.GOOGLE_SERVICES_JSON_BASE64 }}" | base64 --decode > robot/google-services.json
          echo "${{ secrets.GOOGLE_SERVICES_JSON_BASE64 }}" | base64 --decode > robot/src/main/assets/google-services.json
      - name: Decode Release Keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > release.keystore
      - name: Assemble Release Apk
        id: assemble_release_apk
        run: |
          ./gradlew assembleRelease \
            -Pandroid.injected.signing.store.file=$PWD/release.keystore \
            -Pandroid.injected.signing.store.password=$KEYSTORE_PASSWORD \
            -Pandroid.injected.signing.key.alias=$KEY_ALIAS \
            -Pandroid.injected.signing.key.password=$KEY_PASSWORD
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
      - name: Specify Release Asset Paths
        id: asset_paths
        run:  |
          echo "openbot_apk_path=$(pwd)/robot/build/outputs/apk/release/robot-release.apk" >> "$GITHUB_OUTPUT"
          echo "controller_apk_path=$(pwd)/controller/build/outputs/apk/release/controller-release.apk" >> "$GITHUB_OUTPUT"
      - name: Upload OpenBot Asset
        uses: actions/upload-artifact@v4
        with:
          name: OpenBot-APK
          path: ${{ steps.asset_paths.outputs.openbot_apk_path }}
      - name: Upload Controller Asset
        uses: actions/upload-artifact@v4
        with:
          name: Controller-APK
          path: ${{ steps.asset_paths.outputs.controller_apk_path }}
